#!/bin/bash

set -eu

OPT_NO_COPY=${SQUASHFUSED_NO_COPY:-false}

BRIDGE_DIR_CONT_PATH="/squashfused/bridge_dir"
BRIDGE_FIFO_CONT_PATH="/squashfused/bridge_fifo"
DSTTOID_MAP_DIR_CONT_PATH="/tmp/squashfused-map"
LOG_CONT_PATH="/tmp/squashfused.log"

log() {
  echo "[$(date +%Y-%m-%d:%H:%M.%3N)] (id ${SQUASHFS_ID:-?}) ""$@" >>$LOG_CONT_PATH
}

# Find a proper ID.
SQUASHFS_ID=0
while [[ -d "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount" ]]; do
  (( SQUASHFS_ID = SQUASHFS_ID + 1 ))
done

log "squashfs id: $SQUASHFS_ID"

# Classify arguments.
SRCPATH=""
DSTPATH=""
OPTS=""
EXTRAS=""

for ARG in "$@"; do
  case $ARG in
    -*)
      OPTS="$OPTS $ARG"
      ;;
    *)
      if [[ -z "$SRCPATH" ]]; then
        SRCPATH="$ARG"
      elif [[ -z "$DSTPATH" ]]; then
        DSTPATH="$ARG"
      else
        EXTRAS="$EXTRAS $ARG"
      fi
      ;;
  esac
done

log "srcpath: $SRCPATH"
log "dstpath: $DSTPATH"
log "opts: $OPTS"

# TODO: collect "<id>.{out,err,sqfs,mount}" to "<id>/{out,err,sqfs,mount}".
if [[ -f "$SRCPATH" ]]; then
  # TODO: print a warning instead if the '--no-link' option is set.
  if [[ ! -d "$DSTPATH" ]] || [[ ! -z "$(find "$DSTPATH" -mindepth 1 -maxdepth 1)" ]]; then 
    echo "--- from stub ---"
    echo "error: mount destination either doesn't exist or isn't empty"
    exit 1
  fi

  log "mount"

  if [[ "$OPT_NO_COPY" == "false" ]]; then
    # Copy the requested SquashFS image to the bridge directory.
    echo "-- from stub --"
    echo "info: copying image..."
    cp "$SRCPATH" "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.sqfs"
  fi

  # Request a squashfs mount to the delegate daemon.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "mount",                   '\
    '  "opts": "'"$OPTS"'",               '\
    '  "extras": "'"$EXTRAS"'"            '\
    '  "should_map": "'"$OPT_NO_COPY'",   '\
    '  "srcpath": "'"$(readlink -f "$SRCPATH")'"'\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  while [[ ! -f "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.done" ]]; do
    sleep 0.1
  done

  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" ]]; then
    echo "-- from squashfuse --"
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out"
  fi 

  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" ]]; then
    echo "-- from squashfuse --" >&2
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" >&2
  fi 

  rm "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.done"

  if [[ -d "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount" ]]; then
    # TODO: add a '--no-link' option, which doesn't create a link to the
    # destination but prints the path to the actual mounted directory.
    REAL_DSTPATH=$(readlink -f "$DSTPATH")
    rmdir "$REAL_DSTPATH"

    # TODO: link/print the bridge directory path, if the '--no-multiple-mounts' option is set.
    ln -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount" "$REAL_DSTPATH"
  fi
else
  log "forward"

  # Forward the arguments to the delegate daemon.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "forward",                 '\
    '  "args": "'"$@"'"                   '\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  while [[ ! -f "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.done" ]]; do
    sleep 0.1
  done
  
  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" ]]; then
    echo "-- from squashfuse --"
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out"
  fi

  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" ]]; then
    echo "-- from squashfuse --" >&2
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" >&2
  fi

  rm "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.done"

  # Clean up leftover.
  rm "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out"
  rm "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" 
fi
