#!/bin/bash

exec 3>/tmp/hook-log-3
CONTAINER_STATE=$(cat)

state::read() {
  local field=$1
  echo "$CONTAINER_STATE" | jq "$field"
}

#--

echo "squashfused-clean" >&3

SQUASHFUSED_MAP_DIR_PATH="/tmp/squashfused-map"
DAEMON_ID=$(cat "$SQUASHFUSED_MAP_DIR_PATH/$(state::read '.id')")
SQUASHFUSED_DIR_HOST_PATH="/tmp/squashfused-$DAEMON_ID"

DAEMON_PID=$(cat "$SQUASHFUSED_DIR_HOST_PATH"/daemon_pid)

echo "$(state::read '.')" >&3
echo "daemon: $DAEMON_PID" >&3

kill -9 $DAEMON_PID

rm -rf "$SQUASHFUSED_DIR_HOST_PATH"
rm -f "$SQUASHFUSED_MAP_DIR_PATH/$(state::read ',id')"
