#!/bin/bash

OPT_SRCMODE=@SQUASHFUSED_SRCMODE@
OPT_DSTMODE=@SQUASHFUSED_DSTMODE@
OPT_CONSTDST=$(readlink -f @SQUASHFUSED_CONSTDST@ 2>/dev/null || echo "")

if [[ "${1:-}" != "-u" ]]; then
  echo "fusermount-stub: error: only '-u' is supported."
  exit 1
fi

if [[ -z "${2:-}" ]]; then
  if [[ "$OPT_DSTMODE" == "link" ]] || [[ "$OPT_DSTMODE" == "bind" ]]; then
    echo "fusermount-stub: error: no target destination path provided."
    exit 1
  fi
fi

set -eu

BRIDGE_DIR_CONT_PATH="/squashfused/bridge_dir"
BRIDGE_FIFO_CONT_PATH="/squashfused/bridge_fifo"
LOG_CONT_PATH="/tmp/squashfused.log"

log() {
  echo "[$(date +%Y-%m-%d:%H:%M.%3N)] (id ${SQUASHFS_ID:-?}) ""$@" >>$LOG_CONT_PATH
}

DSTPATH=$(echo "${2:-}" | sed 's-/*$--g')
REAL_DSTPATH=$(readlink -f "$DSTPATH" || echo "$DSTPATH")
log "dstpath: $DSTPATH"
log "real dstpath: $REAL_DSTPATH"

if [[ "$OPT_DSTMODE" != "const" ]]; then
  if [[ ! -d "$REAL_DSTPATH" ]]; then
    echo "fusermount-stub: error: '$2' is not a valid path."
    exit 1
  fi
else
  if [[ -n "$DSTPATH" ]] && [[ "$REAL_DSTPATH" != "$OPT_CONSTDST" ]]; then
    echo "fusermount-stub: error: mountpoint should be empty or the same as 'constdst'."
    exit 1
  fi
fi

# Find a proper ID.
SQUASHFS_ID="?"
if [[ "$OPT_DSTMODE" == "const" ]]; then
  # If 'constdst' is set, 'SQUASHFS_ID' must be 0.
  SQUASHFS_ID="0"
elif [[ "$OPT_DSTMODE" == "link" ]] || [[ "$OPT_DSTMODE" == "null" ]]; then
  if echo "$REAL_DSTPATH" | grep "$BRIDGE_DIR_CONT_PATH/[0-9]\+/mount" >/dev/null 2>&1; then
    __SQUASHFS_ID=${REAL_DSTPATH#$BRIDGE_DIR_CONT_PATH/}
    SQUASHFS_ID=${__SQUASHFS_ID%/mount}
  fi
fi

# The unmount request could have been made directly to the mountpoint
# even if there is a symlink to that. Fix 'DSTPATH' if that's the case.
if [[ "$OPT_DSTMODE" == "link" ]]; then
  if [[ -d "$DSTPATH" ]] && [[ ! -h "$DSTPATH" ]]; then
    # Assume 'DSTPATH' is directly given a directory path.
    DSTPATH=$(cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/link")
  fi
fi

log "squashfs id: $SQUASHFS_ID"
if [[ "$SQUASHFS_ID" == "?" ]]; then
  echo "fusermount-stub: error: cannot derive a squashfs file id."
  exit 1
fi

# Request unmount to the daemon.
echo \
  '{                                    '\
  '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
  '  "mode": "unmount"                  '\
  '}                                    '\
  >"$BRIDGE_FIFO_CONT_PATH"

while [[ ! -f "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/done" ]]; do
  sleep 0.1
done

cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/out" | sed 's/^/fusermount: /g'
cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/err" | sed 's/^/fusermount: /g' >&2

# Fix the destination mount point.
if [[ "$OPT_DSTMODE" == "link" ]]; then
  rm "$DSTPATH"
  mkdir "$DSTPATH"
fi

# Send cleanup.
echo \
  '{                                    '\
  '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
  '  "mode": "cleanup"                  '\
  '}                                    '\
  >"$BRIDGE_FIFO_CONT_PATH"
