#!/bin/bash

set -eu

OPT_NO_COPY=${SQUASHFUSED_NO_COPY:-0}
OPT_NO_LINK=${SQUASHFUSED_NO_LINK:-0}

BRIDGE_DIR_CONT_PATH="/squashfused/bridge_dir"
BRIDGE_FIFO_CONT_PATH="/squashfused/bridge_fifo"
DSTTOID_MAP_DIR_CONT_PATH="/tmp/squashfused-map"
LOG_CONT_PATH="/tmp/squashfused.log"

log() {
  echo "[$(date +%Y-%m-%d:%H:%M.%3N)] (id ${SQUASHFS_ID:-?}) ""$@" >>$LOG_CONT_PATH
}

# Find a proper ID.
SQUASHFS_ID=0
while [[ -d "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount" ]]; do
  (( SQUASHFS_ID = SQUASHFS_ID + 1 ))
done

log "squashfs id: $SQUASHFS_ID"

# Classify arguments.
SRCPATH=""
DSTPATH=""
OPTS=""
EXTRAS=""

for ARG in "$@"; do
  case $ARG in
    -*)
      OPTS="$OPTS $ARG"
      ;;
    *)
      if [[ -z "$SRCPATH" ]]; then
        SRCPATH="$(readlink -f $ARG)"
      elif [[ -z "$DSTPATH" ]]; then
        DSTPATH="$(readlink -f $ARG)"
      else
        EXTRAS="$EXTRAS $ARG"
      fi
      ;;
  esac
done

log "srcpath: $SRCPATH"
log "dstpath: $DSTPATH"
log "opts: $OPTS"

echo "squashfuse-stub: '$SRCPATH' to '$DSTPATH'"

# TODO: collect "<id>.{out,err,sqfs,mount}" to "<id>/{out,err,sqfs,mount}".
if [[ -f "$SRCPATH" ]]; then
  log "mount"

  if [[ ! -d "$DSTPATH" ]] || [[ ! -z "$(find "$DSTPATH" -mindepth 1 -maxdepth 1)" ]]; then 
    echo "squashfuse-stub: nonexistent or non-empty mount destination."
    if [[ "$OPT_NO_LINK" != "1" ]]; then
      exit 1
    fi
  fi

  if [[ "$OPT_NO_COPY" == "0" ]]; then
    # Copy the requested SquashFS image to the bridge directory.
    echo "squashfuse-stub: copying image..."
    cp "$SRCPATH" "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.sqfs"
  fi

  # Request a squashfs mount to the delegate daemon.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "mount",                   '\
    '  "opts": "'"$OPTS"'",               '\
    '  "extras": "'"$EXTRAS"'",           '\
    '  "srcpath": "'"$(readlink -f "$SRCPATH")"'"'\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  while [[ ! -f "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.done" ]]; do
    sleep 0.1
  done

  # Print outputs from the actual squashfuse.
  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" | sed 's/^/squashfuse: /g'
  fi 

  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" | sed 's/^/squashfuse: /g' >&2
  fi 

  # Send ack.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "ack"                      '\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  # If the mount was successful, create a link to it.
  if [[ -d "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount" ]]; then
    # TODO: add a '--no-link' option, which doesn't create a link to the
    # destination but prints the path to the actual mounted directory.
    REAL_DSTPATH=$(readlink -f "$DSTPATH")
    rmdir "$REAL_DSTPATH"

    ln -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount" "$REAL_DSTPATH"
  else
    # Send cleanup.
    echo \
      '{                                    '\
      '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
      '  "mode": "cleanup"                  '\
      '}                                    '\
      >"$BRIDGE_FIFO_CONT_PATH"
  fi
else
  log "forward"

  # Forward the arguments to the delegate daemon.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "forward",                 '\
    '  "args": "'"$@"'"                   '\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  while [[ ! -f "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.done" ]]; do
    sleep 0.1
  done

  # Print outputs from the actual squashfuse.
  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" | sed 's/^/squashfuse: /g'
  fi

  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" | sed 's/^/squashfuse: /g' >&2
  fi

  # Send ack.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "ack"                      '\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  # Send cleanup.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "cleanup"                  '\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"
fi
