#!/bin/bash

set -eu

OPT_NOCOPY=${SQUASHFUSED_NOCOPY:-0}
OPT_NOLINK=${SQUASHFUSED_NOLINK:-0}

BRIDGE_DIR_CONT_PATH="/squashfused/bridge_dir"
BRIDGE_FIFO_CONT_PATH="/squashfused/bridge_fifo"
DSTTOID_MAP_DIR_CONT_PATH="/tmp/squashfused-map"
LOG_CONT_PATH="/tmp/squashfused.log"

log() {
  echo "[$(date +%Y-%m-%d:%H:%M.%3N)] (id ${SQUASHFS_ID:-?}) ""$@" >>$LOG_CONT_PATH
}

# Find a proper ID.
SQUASHFS_ID=0
while [[ -d "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount" ]]; do
  (( SQUASHFS_ID = SQUASHFS_ID + 1 ))
done

log "squashfs id: $SQUASHFS_ID"

# Classify arguments.
SRCPATH=""
DSTPATH=""
OPTS=""
EXTRAS=""

for ARG in "$@"; do
  case $ARG in
    -*)
      OPTS="$OPTS $ARG"
      ;;
    *)
      if [[ -z "$SRCPATH" ]]; then
        SRCPATH="$(readlink -f $ARG)"
      elif [[ -z "$DSTPATH" ]]; then
        DSTPATH="$(readlink -f $ARG)"
      else
        EXTRAS="$EXTRAS $ARG"
      fi
      ;;
  esac
done

log "srcpath: $SRCPATH"
log "dstpath: $DSTPATH"
log "opts: $OPTS"

# TODO: collect "<id>.{out,err,sqfs,mount}" to "<id>/{out,err,sqfs,mount}".
if [[ -f "$SRCPATH" ]]; then
  log "mount"

  if [[ "$OPT_NOLINK" != "1" ]]; then
    if [[ ! -d "$DSTPATH" ]] || [[ ! -z "$(find "$DSTPATH" -mindepth 1 -maxdepth 1)" ]]; then 
      echo "squashfuse-stub: error: nonexistent or non-empty mount destination."
      exit 1
    fi
  fi

  _MOUNT_ECHO_PREFIX=""
  if [[ "$OPT_NOLINK" != "1" ]]; then
    _MOUNT_ECHO_PREFIX=" to '$DSTPATH'"
  fi
  echo "squashfuse-stub: mounting '$SRCPATH'${_MOUNT_ECHO_PREFIX}..."

  if [[ "$OPT_NOCOPY" == "0" ]]; then
    # Copy the requested SquashFS image to the bridge directory.
    echo "squashfuse-stub: copying image..."
    cp "$SRCPATH" "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.sqfs"
  fi

  # Request a squashfs mount to the delegate daemon.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "mount",                   '\
    '  "opts": "'"$OPTS"'",               '\
    '  "extras": "'"$EXTRAS"'",           '\
    '  "srcpath": "'"$(readlink -f "$SRCPATH")"'"'\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  while [[ ! -f "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.done" ]]; do
    sleep 0.1
  done

  # Print outputs from the actual squashfuse.
  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" | sed 's/^/squashfuse: /g'
  fi 

  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" | sed 's/^/squashfuse: /g' >&2
  fi 

  # If the mount was successful, create a link to it.
  if [[ -d "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount" ]]; then
    # Create a link if 'nolink' is unset, otherwise report the mountpoint.
    if [[ "$OPT_NOLINK" != "1" ]]; then
      REAL_DSTPATH=$(readlink -f "$DSTPATH")
      rmdir "$REAL_DSTPATH"
      ln -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount" "$REAL_DSTPATH"
    else
      echo "squashfuse-stub: mounted to '"$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.mount"'."
    fi

    # Send ack.
    echo \
      '{                                    '\
      '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
      '  "mode": "ack"                      '\
      '}                                    '\
      >"$BRIDGE_FIFO_CONT_PATH"
  else
    if [[ "$OPT_NOCOPY" == "1" ]]; then
      echo "squashfuse-stub: hint: 'nocopy' is on. image might not be visible to the host."
    fi
    
    # Send cleanup.
    echo \
      '{                                    '\
      '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
      '  "mode": "cleanup"                  '\
      '}                                    '\
      >"$BRIDGE_FIFO_CONT_PATH"
  fi
else
  log "forward"

  echo "squashfuse-stub: cannot find '"$SRCPATH"'. forwarding arguments..."

  # Forward the arguments to the delegate daemon.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "forward",                 '\
    '  "args": "'"$@"'"                   '\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  while [[ ! -f "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.done" ]]; do
    sleep 0.1
  done

  # Print outputs from the actual squashfuse.
  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.out" | sed 's/^/squashfuse: /g'
  fi

  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID.err" | sed 's/^/squashfuse: /g' >&2
  fi

  # Send cleanup.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "cleanup"                  '\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"
fi
