#!/bin/bash

set -eu

OPT_SRCMODE=@SQUASHFUSED_SRCMODE@
OPT_DSTMODE=@SQUASHFUSED_DSTMODE@
OPT_CONSTDST=$(readlink -f @SQUASHFUSED_CONSTDST@ 2>/dev/null || echo "")

BRIDGE_DIR_CONT_PATH="/squashfused/bridge_dir"
BRIDGE_FIFO_CONT_PATH="/squashfused/bridge_fifo"
DSTTOID_MAP_DIR_CONT_PATH="/tmp/squashfused-map"
LOG_CONT_PATH="/tmp/squashfused.log"

log() {
  echo "[$(date +%Y-%m-%d:%H:%M.%3N)] (id ${SQUASHFS_ID:-?}) ""$@" >>$LOG_CONT_PATH
}

# Find a proper ID.
SQUASHFS_ID=0
while [[ -d "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/mount" ]]; do
  (( SQUASHFS_ID = SQUASHFS_ID + 1 ))
done

log "squashfs id: $SQUASHFS_ID"

# Classify arguments.
SRCPATH=""
DSTPATH=""
OPTS=""
EXTRAS=""

for ARG in "$@"; do
  case $ARG in
    -*)
      OPTS="$OPTS $ARG"
      ;;
    *)
      if [[ -z "$SRCPATH" ]]; then
        SRCPATH="$ARG"
      elif [[ -z "$DSTPATH" ]]; then
        DSTPATH="$ARG"
      else
        EXTRAS="$EXTRAS $ARG"
      fi
      ;;
  esac
done

log "srcpath: $SRCPATH"
log "dstpath: $DSTPATH"
log "opts: $OPTS"

if [[ -f "$SRCPATH" ]]; then
  log "mount"

  if [[ "$OPT_DSTMODE" != "null" ]] && [[ "$OPT_DSTMODE" != "const" ]]; then
    if [[ ! -d "$DSTPATH" ]] || [[ -L "$DSTPATH" ]] || [[ ! -z "$(find "$DSTPATH" -mindepth 1 -maxdepth 1)" ]]; then 
      echo "squashfuse-stub: error: nonexistent or non-empty mount destination."
      exit 1
    fi
  fi

  if [[ "$OPT_DSTMODE" == "const" ]] && [[ -n $(find "$OPT_CONSTDST" -mindepth 1 -maxdepth 1) ]]; then
    echo "squashfuse-stub: error: 'constdst' seems mounted."
    exit 1
  fi

  _MOUNT_ECHO_PREFIX=""
  if [[ "$OPT_DSTMODE" != "null" ]] && [[ "$OPT_DSTMODE" != "const" ]]; then
    _MOUNT_ECHO_PREFIX=" to '$DSTPATH'"
  fi
  echo "squashfuse-stub: mounting '$SRCPATH'${_MOUNT_ECHO_PREFIX}..."

  if [[ "$OPT_SRCMODE" == "copy" ]]; then
    # Copy the requested SquashFS image to the bridge directory.
    echo "squashfuse-stub: copying image..."
    mkdir -p "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID"
    cp "$SRCPATH" "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/sqfs"
  fi

  # Request a squashfs mount to the delegate daemon.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "mount",                   '\
    '  "opts": "'"$OPTS"'",               '\
    '  "extras": "'"$EXTRAS"'",           '\
    '  "srcpath": "'"$(readlink -f "$SRCPATH")"'",'\
    '  "dstpath": "'"$(realpath -s "$DSTPATH" 2>/dev/null || true)"'"'\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  while [[ ! -f "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/done" ]]; do
    sleep 0.1
  done

  # Print outputs from the actual squashfuse.
  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/out" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/out" | sed 's/^/squashfuse: /g'
  fi 

  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/err" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/err" | sed 's/^/squashfuse: /g' >&2
  fi 

  # If the mount was successful, do follow-up tasks.
  REGULAR_DSTPATH="$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/mount"
  if [[ -d "$REGULAR_DSTPATH" ]]; then
    if [[ "$OPT_DSTMODE" == "link" ]]; then
      # Create a link to the requested destination.
      REAL_DSTPATH=$(readlink -f "$DSTPATH")
      rmdir "$REAL_DSTPATH"
      ln -s "$REGULAR_DSTPATH" "$REAL_DSTPATH"
    elif [[ "$OPT_DSTMODE" == "bind" ]]; then
      # Check the bind-mount was successful.
      if [[ "$(cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/link")" == "$REGULAR_DSTPATH" ]]; then
        echo "squashfuse-stub: warning: request destination not bind-mounted."
        echo "squashfuse-stub: mounted to '"$REGULAR_DSTPATH"'."
      fi 
    elif [[ "$OPT_DSTMODE" == "null" ]]; then
      # Report the mountpoint.
      echo "squashfuse-stub: mounted to '"$REGULAR_DSTPATH"'."
    fi

    # Send ack.
    echo \
      '{                                    '\
      '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
      '  "mode": "ack"                      '\
      '}                                    '\
      >"$BRIDGE_FIFO_CONT_PATH"
  else
    if [[ "$OPT_SRCMODE" != "copy" ]]; then
      echo "squashfuse-stub: hint: image might not be visible to the host."
    fi
    
    # Send cleanup.
    echo \
      '{                                    '\
      '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
      '  "mode": "cleanup"                  '\
      '}                                    '\
      >"$BRIDGE_FIFO_CONT_PATH"
    
    exit 1
  fi
else
  log "forward"

  echo "squashfuse-stub: cannot find '"$SRCPATH"'. forwarding arguments..."

  # Forward the arguments to the delegate daemon.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "forward",                 '\
    '  "args": "'"$@"'"                   '\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  while [[ ! -f "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/done" ]]; do
    sleep 0.1
  done

  # Print outputs from the actual squashfuse.
  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/out" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/out" | sed 's/^/squashfuse: /g'
  fi

  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/err" ]]; then
    cat "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/err" | sed 's/^/squashfuse: /g' >&2
  fi

  # Send cleanup.
  echo \
    '{                                    '\
    '  "squashfs_id": "'"$SQUASHFS_ID"'", '\
    '  "mode": "cleanup"                  '\
    '}                                    '\
    >"$BRIDGE_FIFO_CONT_PATH"

  # TODO: exit with the actual return code.
  if [[ -s "$BRIDGE_DIR_CONT_PATH/$SQUASHFS_ID/err" ]]; then
    exit 1
  fi
fi
