#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

log::file "/tmp/squashfused-clean.log"
log::echo "squashfused-clean"

state::load

CONTAINER_ID=$(state::read '.id')
DAEMON_ID=$(cat $(path::container_id_to_daemon_id $CONTAINER_ID))

path::set_host "$DAEMON_ID"

log::echo "daemon id: $DAEMON_ID"
log::echo "daemon pid path: $DAEMON_PID_PATH"

DAEMON_PID=$(cat "$DAEMON_PID_PATH")
log::echo "daemon pid: $DAEMON_PID"

kill -9 $DAEMON_PID

log::echo "$(state::read '.')"

umount "$BRIDGE_DIR_HOST_PATH" || true
rm -rf "$DAEMON_DIR_HOST_PATH"
rm -f "$SERVER_DIR_PATH/$CONTAINER_ID"
