#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

state::load
CONTAINER_ID=$(state::read '.id')
DAEMON_ID=$(cat $(path::container_id_to_daemon_id $CONTAINER_ID))

# Set up logging.
log::file "$SERVER_LOG_DIR_PATH/clean-$DAEMON_ID.log"
log::echo "squashfused-clean-$DAEMON_ID"

path::set_host "$DAEMON_ID"
DAEMON_PID=$(cat "$DAEMON_PID_PATH")

log::echo "daemon id: $DAEMON_ID"
log::echo "daemon pid path: $DAEMON_PID_PATH"
log::echo "daemon pid: $DAEMON_PID"

# Kill the daemon.
kill -9 $DAEMON_PID || true

log::echo "bridge dir host path: $BRIDGE_DIR_HOST_PATH"
log::echo "daemon dir host path: $DAEMON_DIR_HOST_PATH"
log::echo "map file path: $(path::container_id_to_daemon_id $CONTAINER_ID)"

# Clean up the files related to the late daemon.
for _MAYBE_MOUNT_PATH in $(find "$BRIDGE_DIR_HOST_PATH" -type d -mindepth 2 -maxdepth 2); do
  umount "$_MAYBE_MOUNT_PATH" || true
done

if [[ -d "$CONST_DST_HOST_PATH" ]]; then
  umount "$CONST_DST_HOST_PATH" || true
fi

rm -rf "$DAEMON_DIR_HOST_PATH"
rm -f "$(path::container_id_to_daemon_id $CONTAINER_ID)"

log::echo "$(state::read '.')"

# Poorman's attempt to avoid log flooding.
# Keep the number of log files under a constant value.
# Remove the oldest modified log, if necessary.
NR_MAX_LOG_FILES=20
while (( $(ls "$SERVER_LOG_DIR_PATH" | wc -w) > $NR_MAX_LOG_FILES )); do
  find "$SERVER_LOG_DIR_PATH" -type f -printf '%T+ %p\n' | sort | head -n 1 | cut -d' ' -f2 | xargs rm
done
