#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

OPT_NOCOPY=@SQUASHFUSED_NOCOPY@
OPT_NOLINK=@SQUASHFUSED_NOLINK@
OPT_CONSTDST=@SQUASHFUSED_CONSTDST@

DAEMON_ID=$1
MOUNT_MAP_RAW=$2

jq::get() {
  echo "$1" | jq -r "$2"
}

path::set_server

# Set up logging.
log::file "$SERVER_LOG_DIR_PATH/daemon-$DAEMON_ID.log"
log::echo "squashfused-daemon-$DAEMON_ID"

path::set_host "$DAEMON_ID"

# Create a mount map.
declare -A MOUNT_MAP
while read MOUNT_MAP_RAW_ELEM; do
  if [[ "$(jq::get "$MOUNT_MAP_RAW_ELEM" '.type')" == "bind" ]]; then
    _SRC=$(jq::get "$MOUNT_MAP_RAW_ELEM" '.source')
    _DST=$(jq::get "$MOUNT_MAP_RAW_ELEM" '.destination')
    MOUNT_MAP[$_DST]=$_SRC
    log::echo "mount entry: $MOUNT_MAP_RAW_ELEM"
  fi
done < <(echo "$MOUNT_MAP_RAW" | jq -c '.[]')
log::echo "mount to: ${!MOUNT_MAP[*]}"
log::echo "mount from: ${MOUNT_MAP[*]}"

log::echo "owner uid \"$DAEMON_DIR_HOST_PATH\": $(stat "$DAEMON_DIR_HOST_PATH")"

# This will be derived on demand.
ROOTFS_PATH="?"

log::echo "$(id)"
while IFS= read -r CMD <"$BRIDGE_FIFO_HOST_PATH"; do
  if [[ "$ROOTFS_PATH" == "?" ]]; then
    _CONTAINER_ID=$(cat $(path::daemon_id_to_container_id $DAEMON_ID) || true)
    if [[ -n "$_CONTAINER_ID" ]]; then
      _CONTAINER_PID=$(podman inspect $_CONTAINER_ID --format {{.State.Pid}} || true)
      if [[ -n "$_CONTAINER_PID" ]] && ls /proc/$_CONTAINER_PID/root/ >/dev/null 2>&1; then
        ROOTFS_PATH="/proc/$_CONTAINER_PID/root"
      fi
    fi
  fi

  log::echo "$(echo "$CMD" | jq '.')"

  SQUASHFS_ID=$(jq::get "$CMD" '.squashfs_id')
  MODE=$(jq::get "$CMD" '.mode')
  STDOUT_PATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/out"
  STDERR_PATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/err"

  mkdir -p "$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID"
  
  case $MODE in
    forward)
      ARGS=$(jq::get "$CMD" '.args')
      squashfuse $ARGS >"$STDOUT_PATH" 2>"$STDERR_PATH" || true
      ;;
    mount)
      OPTS=$(jq::get "$CMD" '.opts')
      EXTRAS=$(jq::get "$CMD" '.extras')
      LN_DSTPATH=$(jq::get "$CMD" '.dstpath')

      if [[ "$OPT_NOCOPY" == "1" ]]; then
        _SRCPATH=$(jq::get "$CMD" '.srcpath')
        log::echo "requested srcpath: $_SRCPATH"

        # Find the mount source path.
        SRCPATH="/nonexistent"

        # If `ROOTFS_PATH` is available, use it. 
        if [[ "$ROOTFS_PATH" != "?" ]]; then
          MAYBE_SRCPATH="$ROOTFS_PATH""$_SRCPATH"
          if [[ -f "$MAYBE_SRCPATH" ]]; then
            SRCPATH=$MAYBE_SRCPATH
          else
            # Otherwise, match the longest to the forwarded source path.
            _SRCPATH_MATCH_LEN=0
            for MOUNT_DSTPATH in ${!MOUNT_MAP[*]}; do
              _MATCH_LEN=$(echo "$_SRCPATH" | grep -o "^$MOUNT_DSTPATH" | wc -c)
              if (( _MATCH_LEN > _SRCPATH_MATCH_LEN )); then
                log::echo "matched: $MOUNT_DSTPATH"
                _SRCPATH_MATCH_LEN=$_MATCH_LEN
                SRCPATH="${MOUNT_MAP[$MOUNT_DSTPATH]}/$(echo "$_SRCPATH" | sed "s@^$MOUNT_DSTPATH@@g")"
              fi
            done
          fi
        fi
      else
        SRCPATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/sqfs"
      fi

      log::echo "final srcpath: $SRCPATH"

      # 'PROT_DSTPATH' is a protocol destination path, whose existence signals
      # a successful mount. When 'constdst' is unset (by default), 
      # this is the same as the actual mount destionation path.
      PROT_DSTPATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/mount"
      mkdir "$PROT_DSTPATH"

      if [[ -n "$OPT_CONSTDST" ]]; then
        DSTPATH="$CONST_DST_HOST_PATH"
      else
        DSTPATH="$PROT_DSTPATH"
      fi

      if ! squashfuse $OPTS "$SRCPATH" "$DSTPATH" $EXTRAS >"$STDOUT_PATH" 2>"$STDERR_PATH"; then
        rmdir "$PROT_DSTPATH"
      fi 

      echo "$LN_DSTPATH" >"$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/link"
      ;;
    unmount)
      MOUNT_PATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/mount"
      if [[ -n "$OPT_CONSTDST" ]]; then
        MOUNT_PATH="$CONST_DST_HOST_PATH"
      fi
      
      umount "$MOUNT_PATH" >"$STDOUT_PATH" 2>"$STDERR_PATH" || true
      ;;
    ack)
      rm "$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/done"
      ;;
    cleanup)
      rm -rf "$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID" >/dev/null 2>&1 || true
      log::echo "bridge dir ls: $(ls "$BRIDGE_DIR_HOST_PATH")"
      ;;
  esac

  if [[ "$MODE" != "ack" ]] && [[ "$MODE" != "cleanup" ]]; then
    touch "$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/done"
  fi
done
