#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

DAEMON_ID=$1
SQUASHFUSED_OPTS_STR=$2
MOUNT_MAP_RAW=$3

jq::get() {
  echo "$1" | jq -r "$2"
}

# Set up logging.
log::file "$SERVER_LOG_DIR_PATH/daemon-$DAEMON_ID.log"
log::echo "squashfused-daemon-$DAEMON_ID"

path::set_host "$DAEMON_ID"

# Get Squashfused options.
declare -A SQUASHFUSED_OPTS
opt::get SQUASHFUSED_OPTS "$SQUASHFUSED_OPTS_STR"

# Create a mount map.
declare -A MOUNT_MAP
while read MOUNT_MAP_RAW_ELEM; do
  if [[ "$(jq::get "$MOUNT_MAP_RAW_ELEM" '.type')" == "bind" ]]; then
    _SRC=$(jq::get "$MOUNT_MAP_RAW_ELEM" '.source')
    _DST=$(jq::get "$MOUNT_MAP_RAW_ELEM" '.destination')
    MOUNT_MAP[$_DST]=$_SRC
    log::echo "mount entry: $MOUNT_MAP_RAW_ELEM"
  fi
done < <(echo "$MOUNT_MAP_RAW" | jq -c '.[]')
log::echo "mount to: ${!MOUNT_MAP[*]}"
log::echo "mount from: ${MOUNT_MAP[*]}"

log::echo "owner uid \"$DAEMON_DIR_HOST_PATH\": $(stat "$DAEMON_DIR_HOST_PATH")"

log::echo "$(id)"
while IFS= read -r CMD <"$BRIDGE_FIFO_HOST_PATH"; do
  log::echo "$(echo "$CMD" | jq '.')"

  SQUASHFS_ID=$(jq::get "$CMD" '.squashfs_id')
  MODE=$(jq::get "$CMD" '.mode')
  STDOUT_PATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/out"
  STDERR_PATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/err"

  mkdir -p "$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID"
  
  case $MODE in
    forward)
      ARGS=$(jq::get "$CMD" '.args')
      squashfuse $ARGS >"$STDOUT_PATH" 2>"$STDERR_PATH" || true
      ;;
    mount)
      OPTS=$(jq::get "$CMD" '.opts')
      EXTRAS=$(jq::get "$CMD" '.extras')
      LN_DSTPATH=$(jq::get "$CMD" '.dstpath')

      if [[ -v SQUASHFUSED_OPTS[nocopy] ]]; then
        _SRCPATH=$(jq::get "$CMD" '.srcpath')
        log::echo "requested srcpath: $_SRCPATH"
        
        # Find the mount source path that matches the longest to the forwarded source path.
        _SRCPATH_MATCH_LEN=0
        for MOUNT_DSTPATH in ${!MOUNT_MAP[*]}; do
          _MATCH_LEN=$(echo "$_SRCPATH" | grep -o "^$MOUNT_DSTPATH" | wc -c)
          if (( _MATCH_LEN > _SRCPATH_MATCH_LEN )); then
            log::echo "matched: $MOUNT_DSTPATH"
            _SRCPATH_MATCH_LEN=$_MATCH_LEN
            SRCPATH="${MOUNT_MAP[$MOUNT_DSTPATH]}/$(echo "$_SRCPATH" | sed "s@^$MOUNT_DSTPATH@@g")"
          fi
        done
      else
        SRCPATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/sqfs"
      fi

      # 'PROT_DSTPATH' is a protocol destination path, whose existence signals
      # a successful mount. When 'constdst' is unset (by default), 
      # this is the same as the actual mount destionation path.
      PROT_DSTPATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/mount"
      mkdir "$PROT_DSTPATH"

      if [[ -v SQUASHFUSED_OPTS[constdst] ]]; then
        DSTPATH="$CONST_DST_HOST_PATH"
      else
        DSTPATH="$PROT_DSTPATH"
      fi

      if ! squashfuse $OPTS "$SRCPATH" "$DSTPATH" $EXTRAS >"$STDOUT_PATH" 2>"$STDERR_PATH"; then
        rmdir "$PROT_DSTPATH"
      fi 

      echo "$LN_DSTPATH" >"$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/link"
      ;;
    unmount)
      MOUNT_PATH="$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/mount"
      if [[ -v SQUASHFUSED_OPTS[constdst] ]]; then
        MOUNT_PATH="$CONST_DST_HOST_PATH"
      fi
      
      umount "$MOUNT_PATH" >"$STDOUT_PATH" 2>"$STDERR_PATH" || true
      ;;
    ack)
      rm "$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/done"
      ;;
    cleanup)
      rm -rf "$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID" >/dev/null 2>&1 || true
      log::echo "bridge dir ls: $(ls "$BRIDGE_DIR_HOST_PATH")"
      ;;
  esac

  if [[ "$MODE" != "ack" ]] && [[ "$MODE" != "cleanup" ]]; then
    touch "$BRIDGE_DIR_HOST_PATH/$SQUASHFS_ID/done"
  fi
done
