#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

log::file "/tmp/squashfused-forward.log"
log::echo "squashfused-forward"

state::load

log::echo $(whoami)

DAEMON_ID=$(cksum <<< $(state::read '.root') | cut -d' ' -f1)
CONTAINER_ID=$(state::read '.id')
echo "$DAEMON_ID" >"$(path::container_id_to_daemon_id $CONTAINER_ID)"

# DEBUG: log modified OCI runtime spec.
log::echo "$(state::read '.')"

# Print modified OCI runtime spec.
state::print
