#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

path::set_server

state::load
DAEMON_ID=$(cksum <<< $(state::read '.root') | cut -d' ' -f1)

# Set up logging.
log::file "$SERVER_LOG_DIR_PATH/forward-$DAEMON_ID.log"
log::echo "squashfused-forward-$DAEMON_ID"

# Create container-id-to-daemon-id mapping.
CONTAINER_ID=$(state::read '.id')
echo "$DAEMON_ID" >"$(path::container_id_to_daemon_id $CONTAINER_ID)"

# DEBUG: log modified OCI runtime spec.
log::echo "$(state::read '.')"

# Print modified OCI runtime spec.
state::print
