#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh

log::file "/tmp/squashfused-forward.log"
log::echo "squashfused-forward"

state::load

# Create a mapping from the container ID to a daemon ID.
SQUASHFUSED_MAP_DIR_PATH="/tmp/squashfused-map"
mkdir -p "$SQUASHFUSED_MAP_DIR_PATH"

DAEMON_ID=$(cksum <<< $(state::read '.root') | cut -d' ' -f1)
CONTAINER_ID=$(state::read '.id')
echo "$DAEMON_ID" >"$SQUASHFUSED_MAP_DIR_PATH/$CONTAINER_ID"

# DEBUG: log modified OCI runtime spec.
log::echo "$(state::read '.')"

# Print modified OCI runtime spec.
state::print
