#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh

log::file "/tmp/squashfused-init.log"
log::echo "squashfused-init"

state::load

# There is no container ID because, understandably, this is before `create`.
# Instead, use a (pseudo-)hash of the root filesystem path.
DAEMON_ID=$(cksum <<< $(state::read '.root.path') | cut -d' ' -f1)
SQUASHFUSED_DIR_HOST_PATH="/tmp/squashfused-$DAEMON_ID"
SQUASHFUSED_DIR_CONT_PATH="/squashfused"
mkdir -p "$SQUASHFUSED_DIR_HOST_PATH"

# Create a bridge directory.
BRIDGE_DIR_HOST_PATH="$SQUASHFUSED_DIR_HOST_PATH/bridge_dir"
BRIDGE_DIR_CONT_PATH="$SQUASHFUSED_DIR_CONT_PATH/bridge_dir"
mkdir -p "$BRIDGE_DIR_HOST_PATH"

# Create a bridge FIFO.
BRIDGE_FIFO_HOST_PATH="$SQUASHFUSED_DIR_HOST_PATH/bridge_fifo"
BRIDGE_FIFO_CONT_PATH="$SQUASHFUSED_DIR_CONT_PATH/bridge_fifo"
mkfifo "$BRIDGE_FIFO_HOST_PATH"

# Inject briedges.
state::add '.mounts' '
[{ 
  "source": "'"$BRIDGE_DIR_HOST_PATH"'",
  "type": "bind",
  "destination": "'"$BRIDGE_DIR_CONT_PATH"'",
  "options": [ "bind", "nosuid", "shared" ]
}]'

state::add '.mounts' '
[{ 
  "source": "'"$BRIDGE_FIFO_HOST_PATH"'",
  "type": "bind",
  "destination": "'"$BRIDGE_FIFO_CONT_PATH"'",
  "options": [ "bind", "rw" ]
}]'

# Inject stub.
state::add '.mounts' '
[{ 
  "source": "/usr/local/libexec/squashfused/stub/squashfuse",
  "type": "bind",
  "destination": "/usr/bin/squashfuse",
  "options": [ "bind" ]
}]'

log::echo "$(id)"
log::echo "owner uid \"$SQUASHFUSED_DIR_HOST_PATH\": $(stat "$SQUASHFUSED_DIR_HOST_PATH")"

# Start off the delegate daemon.
nohup setsid /usr/local/libexec/squashfused/daemon "$DAEMON_ID" >/dev/null 2>&1 &
DAEMON_PID=$!
echo "$DAEMON_PID" >"$SQUASHFUSED_DIR_HOST_PATH/daemon_pid"
log::echo "$(lsns -p $DAEMON_PID)"

# DEBUG: log modified OCI runtime spec.
log::echo "$(state::read '.')"

# Print modified OCI runtime spec.
state::print
