#!/bin/bash

exec 2>/tmp/err.log

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

OPT_NOCOPY=@SQUASHFUSED_NOCOPY@
OPT_NOLINK=@SQUASHFUSED_NOLINK@
OPT_CONSTDST=@SQUASHFUSED_CONSTDST@

path::set_server

# There is no container ID because, understandably, this is before `create`.
# Instead, use a (pseudo-)hash of the root filesystem path.
state::load
DAEMON_ID=$(cksum <<< $(state::read '.root.path') | cut -d' ' -f1)

# Set up logging.
log::file "$SERVER_LOG_DIR_PATH/init-$DAEMON_ID.log"
log::echo "squashfused-init-$DAEMON_ID"

path::set_host "$DAEMON_ID"

# Start off the delegate daemon.
echo "$DAEMON_ID" >"$SERVER_FIFO_PATH"
echo "$(state::read '.mounts')" >"$SERVER_FIFO_PATH"

# Unidirectional communication (i.e., waiting for the server's response via FIFO)
# could open up the possibility of race conditions down the road.
# Instead, just wait for a PID file that's guaranteed to be created at the end.
while [[ ! -f "$DAEMON_PID_PATH" ]]; do 
  sleep 0.1
done

# If "NO_COPY" was set, there is no reason the bridge directory should be read-write.
BRIDGE_DIR_WRITE_PERM="rw"
if [[ "$OPT_NOCOPY" == "1" ]]; then
  BRIDGE_DIR_WRITE_PERM="ro"
fi

# Inject briedges.
state::add '.mounts' '
[{ 
  "source": "'"$BRIDGE_DIR_HOST_PATH"'",
  "type": "bind",
  "destination": "'"$BRIDGE_DIR_CONT_PATH"'",
  "options": [ "'"$BRIDGE_DIR_WRITE_PERM"'", "slave", "rbind" ]
}]'

state::add '.mounts' '
[{ 
  "source": "'"$BRIDGE_FIFO_HOST_PATH"'",
  "type": "bind",
  "destination": "'"$BRIDGE_FIFO_CONT_PATH"'",
  "options": [ "rw", "rbind" ]
}]'

if [[ -n "$OPT_CONSTDST" ]]; then
  state::add '.mounts' '
  [{ 
    "source": "'"$CONST_DST_HOST_PATH"'",
    "type": "bind",
    "destination": "'"$OPT_CONSTDST"'",
    "options": [ "ro", "slave", "rbind" ]
  }]'
fi

# Allow rootfs mount propagation.
state::add '.linux' '{ "rootfsPropagation": "shared" }'

# Inject stub.
state::add '.mounts' '
[{ 
  "source": "/usr/local/libexec/squashfused/stub/squashfuse",
  "type": "bind",
  "destination": "/usr/bin/squashfuse",
  "options": [ "bind" ]
}]'

## TODO: forward arguments to the real 'fusermount' when not '-u'.
state::add '.mounts' '
[{ 
  "source": "/usr/local/libexec/squashfused/stub/fusermount",
  "type": "bind",
  "destination": "/usr/bin/fusermount",
  "options": [ "bind" ]
}]'

## TODO: only inject when unprivileged.
state::add '.mounts' '
[{ 
  "source": "/usr/local/libexec/squashfused/stub/umount",
  "type": "bind",
  "destination": "/usr/bin/umount",
  "options": [ "bind" ]
}]'

# DEBUG: log modified OCI runtime spec.
log::echo "$(state::read '.')"

# Print modified OCI runtime spec.
state::print
