#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

# There is no container ID because, understandably, this is before `create`.
# Instead, use a (pseudo-)hash of the root filesystem path.
state::load
DAEMON_ID=$(cksum <<< $(state::read '.root.path') | cut -d' ' -f1)

# Set up logging.
log::file "$SERVER_LOG_DIR_PATH/init-$DAEMON_ID.log"
log::echo "squashfused-init-$DAEMON_ID"

path::set_host "$DAEMON_ID"

# Start off the delegate daemon.
echo "$DAEMON_ID" >"$SERVER_FIFO_PATH"
echo "$(state::read '.mounts')" >"$SERVER_FIFO_PATH"

# Unidirectional communication (i.e., waiting for the server's response via FIFO)
# could open up the possibility of race conditions down the road.
# Instead, just wait for a PID file that's guaranteed to be created at the end.
while [[ ! -f "$DAEMON_PID_PATH" ]]; do 
  sleep 0.1
done

# Inject briedges.
# TODO: change the mount option 'shared' to 'slave' if the '--no-copy' option is set.
state::add '.mounts' '
[{ 
  "source": "'"$BRIDGE_DIR_HOST_PATH"'",
  "type": "bind",
  "destination": "'"$BRIDGE_DIR_CONT_PATH"'",
  "options": [ "rw", "shared", "rbind" ]
}]'

state::add '.mounts' '
[{ 
  "source": "'"$BRIDGE_FIFO_HOST_PATH"'",
  "type": "bind",
  "destination": "'"$BRIDGE_FIFO_CONT_PATH"'",
  "options": [ "rw", "rbind" ]
}]'

# Allow rootfs mount propagation.
state::add '.linux' '{ "rootfsPropagation": "shared" }'

# Inject stub.
state::add '.mounts' '
[{ 
  "source": "/usr/local/libexec/squashfused/stub/squashfuse",
  "type": "bind",
  "destination": "/usr/bin/squashfuse",
  "options": [ "bind" ]
}]'

## TODO: forward arguments to the real 'fusermount' when not '-u'.
state::add '.mounts' '
[{ 
  "source": "/usr/local/libexec/squashfused/stub/fusermount",
  "type": "bind",
  "destination": "/usr/bin/fusermount",
  "options": [ "bind" ]
}]'

## TODO: only inject when unprivileged.
state::add '.mounts' '
[{ 
  "source": "/usr/local/libexec/squashfused/stub/umount",
  "type": "bind",
  "destination": "/usr/bin/umount",
  "options": [ "bind" ]
}]'

# TODO: forward '--no-link' and '--direct' options to the stub via an envvar.
# This envvar is okay to be user-controllable because changing the options via
# envvar doesn't manipulate the daemon's behavior (=no host-side effect). It
# only affects the **functionality** of the stub inside the container.
for SQUASHFUSED_ENV in @SQUASHFUSED_ENVS@; do
  state::add '.process.env' "[ \"SQUASHFUSED_$SQUASHFUSED_ENV\" ]" 
done

# DEBUG: log modified OCI runtime spec.
log::echo "$(state::read '.')"

# Print modified OCI runtime spec.
state::print
