#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

# Provision the server directory. 
mkdir -p "$SERVER_DIR_PATH"
mkdir -p "$SERVER_MAP_DIR_PATH"
mkdir -p "$SERVER_LOG_DIR_PATH"
mkfifo "$SERVER_FIFO_PATH" || true

# Set up logging.
log::file "$SERVER_LOG_DIR_PATH/server.log"
log::echo "squashfused-server"

SQUASHFUSED_OPTS_STR=@SQUASHFUSED_OPTS_STR@

# Get Squashfused options.
declare -A SQUASHFUSED_OPTS
opt::get SQUASHFUSED_OPTS "$SQUASHFUSED_OPTS_STR"

# Wait and spawn a daemon on demand.
# ISSUE: sometimes it stucks at reading from the FIFO.
while IFS= read -r DAEMON_ID <"$SERVER_FIFO_PATH"; do
  read -r MOUNT_MAP_RAW <"$SERVER_FIFO_PATH"

  path::set_host "$DAEMON_ID"

  log::echo "daemon id: $DAEMON_ID"

  # Create a bridge directory and FIFO.
  mkdir -p "$BRIDGE_DIR_HOST_PATH"
  mkfifo "$BRIDGE_FIFO_HOST_PATH"

  # If 'constdst' is set, create a constant destiation directory.
  if [[ -v SQUASHFUSED_OPTS[constdst] ]]; then
    mkdir -p "$CONST_DST_HOST_PATH"
  fi

  # Create a delegate daemon.
  nohup setsid /usr/local/libexec/squashfused/daemon "$DAEMON_ID" "$SQUASHFUSED_OPTS_STR" "$MOUNT_MAP_RAW" >/dev/null 2>&1 &
  DAEMON_PID=$!

  log::echo "daemon pid: $DAEMON_PID"

  # Write the daemon's pid (and notify the completion of the daemon creation).
  echo "$DAEMON_PID" >"$DAEMON_PID_PATH"
done
