#!/bin/bash

set -eu
source /usr/local/lib/squashfused/common.sh
source /usr/local/lib/squashfused/path.sh

log::file "/tmp/squashfused-server.log"
log::echo "squashfused-server"

# Create a server directory and FIFO.
mkdir -p "$SERVER_DIR_PATH"
mkfifo "$SERVER_FIFO_PATH" || true

# Wait and spawn a daemon on demand.
# ISSUE: sometimes it stucks at reading from the FIFO.
while IFS= read -r DAEMON_ID <"$SERVER_FIFO_PATH"; do
  path::set_host "$DAEMON_ID"

  # Create a bridge directory and FIFO.
  mkdir -p "$BRIDGE_DIR_HOST_PATH"
  mkfifo "$BRIDGE_FIFO_HOST_PATH"

  # Create a delegate daemon.
  nohup setsid /usr/local/libexec/squashfused/daemon "$DAEMON_ID" >/dev/null 2>&1 &
  DAEMON_PID=$!

  # Write the daemon's pid (and notify the completion of the daemon creation).
  echo "$DAEMON_PID" >"$DAEMON_PID_PATH"
done
